//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQT_CSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENDONGSTK
    {
        public decimal ID { get; set; }
        public string MASTK { get; set; }
        public Nullable<decimal> THANG { get; set; }
        public Nullable<System.DateTime> NGAYTINH { get; set; }
        public Nullable<decimal> TIENGOC { get; set; }
        public Nullable<decimal> LAISUAT { get; set; }
        public Nullable<decimal> TIENLAI { get; set; }
    
        public virtual SOTIETKIEM SOTIETKIEM { get; set; }
    }
}
