//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQT_CSDL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
        public Entities1(string conn) : base(conn)
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GIAODICH> GIAODICHes { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIHINHGD> LOAIHINHGDs { get; set; }
        public virtual DbSet<LOAITIETKIEM> LOAITIETKIEMs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHONGGD> PHONGGDs { get; set; }
        public virtual DbSet<QUAYGD> QUAYGDs { get; set; }
        public virtual DbSet<SOTIETKIEM> SOTIETKIEMs { get; set; }
        public virtual DbSet<BIENDONGSTK> BIENDONGSTKs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
    
        public virtual int SP_THEMNHANVIEN(string v_HOTEN, string v_GIOITINH, Nullable<System.DateTime> v_NGAYSINH, string v_CCCD, string v_DIACHI, string v_SDT, string v_MAQUAY, string v_TENDANGNHAP, string v_MATKHAU, string v_MACV)
        {
            var v_HOTENParameter = v_HOTEN != null ?
                new ObjectParameter("V_HOTEN", v_HOTEN) :
                new ObjectParameter("V_HOTEN", typeof(string));
    
            var v_GIOITINHParameter = v_GIOITINH != null ?
                new ObjectParameter("V_GIOITINH", v_GIOITINH) :
                new ObjectParameter("V_GIOITINH", typeof(string));
    
            var v_NGAYSINHParameter = v_NGAYSINH.HasValue ?
                new ObjectParameter("V_NGAYSINH", v_NGAYSINH) :
                new ObjectParameter("V_NGAYSINH", typeof(System.DateTime));
    
            var v_CCCDParameter = v_CCCD != null ?
                new ObjectParameter("V_CCCD", v_CCCD) :
                new ObjectParameter("V_CCCD", typeof(string));
    
            var v_DIACHIParameter = v_DIACHI != null ?
                new ObjectParameter("V_DIACHI", v_DIACHI) :
                new ObjectParameter("V_DIACHI", typeof(string));
    
            var v_SDTParameter = v_SDT != null ?
                new ObjectParameter("V_SDT", v_SDT) :
                new ObjectParameter("V_SDT", typeof(string));
    
            var v_MAQUAYParameter = v_MAQUAY != null ?
                new ObjectParameter("V_MAQUAY", v_MAQUAY) :
                new ObjectParameter("V_MAQUAY", typeof(string));
    
            var v_TENDANGNHAPParameter = v_TENDANGNHAP != null ?
                new ObjectParameter("V_TENDANGNHAP", v_TENDANGNHAP) :
                new ObjectParameter("V_TENDANGNHAP", typeof(string));
    
            var v_MATKHAUParameter = v_MATKHAU != null ?
                new ObjectParameter("V_MATKHAU", v_MATKHAU) :
                new ObjectParameter("V_MATKHAU", typeof(string));
    
            var v_MACVParameter = v_MACV != null ?
                new ObjectParameter("V_MACV", v_MACV) :
                new ObjectParameter("V_MACV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMNHANVIEN", v_HOTENParameter, v_GIOITINHParameter, v_NGAYSINHParameter, v_CCCDParameter, v_DIACHIParameter, v_SDTParameter, v_MAQUAYParameter, v_TENDANGNHAPParameter, v_MATKHAUParameter, v_MACVParameter);
        }
    
        public virtual int SP_GUITIEN(Nullable<decimal> v_SOTIENGUI, string v_MANV, string v_MASTK)
        {
            var v_SOTIENGUIParameter = v_SOTIENGUI.HasValue ?
                new ObjectParameter("V_SOTIENGUI", v_SOTIENGUI) :
                new ObjectParameter("V_SOTIENGUI", typeof(decimal));
    
            var v_MANVParameter = v_MANV != null ?
                new ObjectParameter("V_MANV", v_MANV) :
                new ObjectParameter("V_MANV", typeof(string));
    
            var v_MASTKParameter = v_MASTK != null ?
                new ObjectParameter("V_MASTK", v_MASTK) :
                new ObjectParameter("V_MASTK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GUITIEN", v_SOTIENGUIParameter, v_MANVParameter, v_MASTKParameter);
        }
    
        public virtual int SP_TATTOANSTK(string v_MASTK, string v_MANV, ObjectParameter v_KQ, ObjectParameter v_SOTIEN)
        {
            var v_MASTKParameter = v_MASTK != null ?
                new ObjectParameter("V_MASTK", v_MASTK) :
                new ObjectParameter("V_MASTK", typeof(string));
    
            var v_MANVParameter = v_MANV != null ?
                new ObjectParameter("V_MANV", v_MANV) :
                new ObjectParameter("V_MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TATTOANSTK", v_MASTKParameter, v_MANVParameter, v_KQ, v_SOTIEN);
        }
    
        public virtual int SP_RUTTIEN(string v_MASTK, Nullable<decimal> v_SOTIEN_RUT, string v_MANV, ObjectParameter v_ERRORCODE)
        {
            var v_MASTKParameter = v_MASTK != null ?
                new ObjectParameter("V_MASTK", v_MASTK) :
                new ObjectParameter("V_MASTK", typeof(string));
    
            var v_SOTIEN_RUTParameter = v_SOTIEN_RUT.HasValue ?
                new ObjectParameter("V_SOTIEN_RUT", v_SOTIEN_RUT) :
                new ObjectParameter("V_SOTIEN_RUT", typeof(decimal));
    
            var v_MANVParameter = v_MANV != null ?
                new ObjectParameter("V_MANV", v_MANV) :
                new ObjectParameter("V_MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RUTTIEN", v_MASTKParameter, v_SOTIEN_RUTParameter, v_MANVParameter, v_ERRORCODE);
        }
    
        public virtual int THEM_SO_TIET_KIEM(string p_MAKH, Nullable<System.DateTime> p_NGAYMOSO, Nullable<System.DateTime> p_NGAYDENHAN, Nullable<decimal> p_SOTIENGUI, string p_MALOAITK, string p_MANV)
        {
            var p_MAKHParameter = p_MAKH != null ?
                new ObjectParameter("P_MAKH", p_MAKH) :
                new ObjectParameter("P_MAKH", typeof(string));
    
            var p_NGAYMOSOParameter = p_NGAYMOSO.HasValue ?
                new ObjectParameter("P_NGAYMOSO", p_NGAYMOSO) :
                new ObjectParameter("P_NGAYMOSO", typeof(System.DateTime));
    
            var p_NGAYDENHANParameter = p_NGAYDENHAN.HasValue ?
                new ObjectParameter("P_NGAYDENHAN", p_NGAYDENHAN) :
                new ObjectParameter("P_NGAYDENHAN", typeof(System.DateTime));
    
            var p_SOTIENGUIParameter = p_SOTIENGUI.HasValue ?
                new ObjectParameter("P_SOTIENGUI", p_SOTIENGUI) :
                new ObjectParameter("P_SOTIENGUI", typeof(decimal));
    
            var p_MALOAITKParameter = p_MALOAITK != null ?
                new ObjectParameter("P_MALOAITK", p_MALOAITK) :
                new ObjectParameter("P_MALOAITK", typeof(string));
    
            var p_MANVParameter = p_MANV != null ?
                new ObjectParameter("P_MANV", p_MANV) :
                new ObjectParameter("P_MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEM_SO_TIET_KIEM", p_MAKHParameter, p_NGAYMOSOParameter, p_NGAYDENHANParameter, p_SOTIENGUIParameter, p_MALOAITKParameter, p_MANVParameter);
        }
    
        public virtual int SUATHONGTINNHANVIEN(string p_MANV, string p_HOTEN, string p_GIOITINH, Nullable<System.DateTime> p_NGAYSINH, string p_CCCD, string p_DIACHI, string p_SDT, string p_TINHTRANG, string p_MAQUAY)
        {
            var p_MANVParameter = p_MANV != null ?
                new ObjectParameter("P_MANV", p_MANV) :
                new ObjectParameter("P_MANV", typeof(string));
    
            var p_HOTENParameter = p_HOTEN != null ?
                new ObjectParameter("P_HOTEN", p_HOTEN) :
                new ObjectParameter("P_HOTEN", typeof(string));
    
            var p_GIOITINHParameter = p_GIOITINH != null ?
                new ObjectParameter("P_GIOITINH", p_GIOITINH) :
                new ObjectParameter("P_GIOITINH", typeof(string));
    
            var p_NGAYSINHParameter = p_NGAYSINH.HasValue ?
                new ObjectParameter("P_NGAYSINH", p_NGAYSINH) :
                new ObjectParameter("P_NGAYSINH", typeof(System.DateTime));
    
            var p_CCCDParameter = p_CCCD != null ?
                new ObjectParameter("P_CCCD", p_CCCD) :
                new ObjectParameter("P_CCCD", typeof(string));
    
            var p_DIACHIParameter = p_DIACHI != null ?
                new ObjectParameter("P_DIACHI", p_DIACHI) :
                new ObjectParameter("P_DIACHI", typeof(string));
    
            var p_SDTParameter = p_SDT != null ?
                new ObjectParameter("P_SDT", p_SDT) :
                new ObjectParameter("P_SDT", typeof(string));
    
            var p_TINHTRANGParameter = p_TINHTRANG != null ?
                new ObjectParameter("P_TINHTRANG", p_TINHTRANG) :
                new ObjectParameter("P_TINHTRANG", typeof(string));
    
            var p_MAQUAYParameter = p_MAQUAY != null ?
                new ObjectParameter("P_MAQUAY", p_MAQUAY) :
                new ObjectParameter("P_MAQUAY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUATHONGTINNHANVIEN", p_MANVParameter, p_HOTENParameter, p_GIOITINHParameter, p_NGAYSINHParameter, p_CCCDParameter, p_DIACHIParameter, p_SDTParameter, p_TINHTRANGParameter, p_MAQUAYParameter);
        }
    
        public virtual int DELETE_EMPLOYEE(string p_EMPLOYEE_ID)
        {
            var p_EMPLOYEE_IDParameter = p_EMPLOYEE_ID != null ?
                new ObjectParameter("P_EMPLOYEE_ID", p_EMPLOYEE_ID) :
                new ObjectParameter("P_EMPLOYEE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_EMPLOYEE", p_EMPLOYEE_IDParameter);
        }
    
        public virtual int UPDATE_CUSTOMER_INFO(string p_MAKH, string p_HOTEN, string p_GIOITINH, Nullable<System.DateTime> p_NGAYSINH, string p_CCCD, string p_DIACHI, string p_SDT, string p_TINHTRANG)
        {
            var p_MAKHParameter = p_MAKH != null ?
                new ObjectParameter("P_MAKH", p_MAKH) :
                new ObjectParameter("P_MAKH", typeof(string));
    
            var p_HOTENParameter = p_HOTEN != null ?
                new ObjectParameter("P_HOTEN", p_HOTEN) :
                new ObjectParameter("P_HOTEN", typeof(string));
    
            var p_GIOITINHParameter = p_GIOITINH != null ?
                new ObjectParameter("P_GIOITINH", p_GIOITINH) :
                new ObjectParameter("P_GIOITINH", typeof(string));
    
            var p_NGAYSINHParameter = p_NGAYSINH.HasValue ?
                new ObjectParameter("P_NGAYSINH", p_NGAYSINH) :
                new ObjectParameter("P_NGAYSINH", typeof(System.DateTime));
    
            var p_CCCDParameter = p_CCCD != null ?
                new ObjectParameter("P_CCCD", p_CCCD) :
                new ObjectParameter("P_CCCD", typeof(string));
    
            var p_DIACHIParameter = p_DIACHI != null ?
                new ObjectParameter("P_DIACHI", p_DIACHI) :
                new ObjectParameter("P_DIACHI", typeof(string));
    
            var p_SDTParameter = p_SDT != null ?
                new ObjectParameter("P_SDT", p_SDT) :
                new ObjectParameter("P_SDT", typeof(string));
    
            var p_TINHTRANGParameter = p_TINHTRANG != null ?
                new ObjectParameter("P_TINHTRANG", p_TINHTRANG) :
                new ObjectParameter("P_TINHTRANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CUSTOMER_INFO", p_MAKHParameter, p_HOTENParameter, p_GIOITINHParameter, p_NGAYSINHParameter, p_CCCDParameter, p_DIACHIParameter, p_SDTParameter, p_TINHTRANGParameter);
        }
    
        public virtual int XOA_KHACH_HANG(string p_MAKH)
        {
            var p_MAKHParameter = p_MAKH != null ?
                new ObjectParameter("P_MAKH", p_MAKH) :
                new ObjectParameter("P_MAKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOA_KHACH_HANG", p_MAKHParameter);
        }
    
        public virtual int THEM_KHACH_HANG(string p_MAKH, string p_HOTEN, string p_GIOITINH, Nullable<System.DateTime> p_NGAYSINH, string p_CCCD, string p_DIACHI, string p_SDT, string p_TINHTRANG)
        {
            var p_MAKHParameter = p_MAKH != null ?
                new ObjectParameter("P_MAKH", p_MAKH) :
                new ObjectParameter("P_MAKH", typeof(string));
    
            var p_HOTENParameter = p_HOTEN != null ?
                new ObjectParameter("P_HOTEN", p_HOTEN) :
                new ObjectParameter("P_HOTEN", typeof(string));
    
            var p_GIOITINHParameter = p_GIOITINH != null ?
                new ObjectParameter("P_GIOITINH", p_GIOITINH) :
                new ObjectParameter("P_GIOITINH", typeof(string));
    
            var p_NGAYSINHParameter = p_NGAYSINH.HasValue ?
                new ObjectParameter("P_NGAYSINH", p_NGAYSINH) :
                new ObjectParameter("P_NGAYSINH", typeof(System.DateTime));
    
            var p_CCCDParameter = p_CCCD != null ?
                new ObjectParameter("P_CCCD", p_CCCD) :
                new ObjectParameter("P_CCCD", typeof(string));
    
            var p_DIACHIParameter = p_DIACHI != null ?
                new ObjectParameter("P_DIACHI", p_DIACHI) :
                new ObjectParameter("P_DIACHI", typeof(string));
    
            var p_SDTParameter = p_SDT != null ?
                new ObjectParameter("P_SDT", p_SDT) :
                new ObjectParameter("P_SDT", typeof(string));
    
            var p_TINHTRANGParameter = p_TINHTRANG != null ?
                new ObjectParameter("P_TINHTRANG", p_TINHTRANG) :
                new ObjectParameter("P_TINHTRANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEM_KHACH_HANG", p_MAKHParameter, p_HOTENParameter, p_GIOITINHParameter, p_NGAYSINHParameter, p_CCCDParameter, p_DIACHIParameter, p_SDTParameter, p_TINHTRANGParameter);
        }
    }
}
