//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQT_CSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.GIAODICHes = new HashSet<GIAODICH>();
            this.SOTIETKIEMs = new HashSet<SOTIETKIEM>();
        }
    
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string TINHTRANG { get; set; }
        public string MAQUAY { get; set; }
        public string MACV { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAODICH> GIAODICHes { get; set; }
        public virtual QUAYGD QUAYGD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOTIETKIEM> SOTIETKIEMs { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
    }
}
