//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQT_CSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOTIETKIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOTIETKIEM()
        {
            this.GIAODICHes = new HashSet<GIAODICH>();
            this.BIENDONGSTKs = new HashSet<BIENDONGSTK>();
        }
    
        public string MASTK { get; set; }
        public string MAKH { get; set; }
        public Nullable<System.DateTime> NGAYMOSO { get; set; }
        public Nullable<System.DateTime> NGAYDENHAN { get; set; }
        public Nullable<decimal> SOTIENGUI { get; set; }
        public string MALOAITK { get; set; }
        public string MANV { get; set; }
        public string TINHTRANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAODICH> GIAODICHes { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAITIETKIEM LOAITIETKIEM { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENDONGSTK> BIENDONGSTKs { get; set; }
    }
}
